version: "3"

services:
  notebook:
    image: jupyter/pyspark-notebook
    user: root
    restart: on-failure
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO=yes
      - NB_UID=1000
      - NB_GID=1000
    ports:
      - "8888:8888"
    volumes:
      - ../work:/home/jovyan/work
      - ../.jupyter:/home/jovyan/.jupyter
      - ../.local/share/jupyter:/home/jovyan/.local/share/jupyter

    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --no-browser"
